name: Build and publish docker image for dispatcher manually

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  dispatcher-docker-manual:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish Docker image manually
      run: bash ./dispatcher/publish_image.sh